#!/bin/bash
while true; do

    cd /pp-cuhacks

    git remote update

    if [[ -z $(git status -uno | grep behind) ]]     # if branch is up to date, do nothing
    then
        echo "do nothing"
    else
        git fetch --all
        git add .
        git reset --hard 
        git pull
        npm i
        npm run build
    fi


    cd /pp-api

    git fetch --all
    git add .
    git reset --hard
    git pull
    npm i
    cp -r /pp-cuhacks/build /pp-api
    npm run build

    echo sleeping 30 s
    sleep 30
    echo "



    "
done